### ISSUE TITLE
Incorrect pinout/missing pins

### ISSUE THREAD

**Issue by WillNilges** [ClearGauntlets/ClearGauntlet-PCB#8]
Rev A is missing pins required for basic operation of the board. Additionally, the pin pattern for power and ground is incorrect.

The pins needed for basic operation are as follows. These ones need to be surrounded by a 3.3V pin and GND pin
- D32: PIN_THUMB **has 5V pin**
- D35: PIN_INDEX **has 5V pin**
- D34: PIN_MIDDLE **has 5V pin**
- D39: PIN_RING **MISSING**
- D36: PIN_PINKY **MISSING**

These ones need to be surrounded by a 5V pin and GND pin.
- D5: PIN_PINKY_MOTOR **has 3.3V pin**
- D18: PIN_RING_MOTOR **has 3.3V pin**
- D19: PIN_MIDDLE_MOTOR  **has 3.3V pin**
- D21: PIN_INDEX_MOTOR  **has 3.3V pin**
- D17: PIN_THUMB_MOTOR **MISSING**

See the [firmware configuration](https://github.com/LucidVR/lucidgloves/blob/8515b110362a13a2abf119d287870a31e65aa666/firmware/lucidgloves-firmware/lucidgloves-firmware.ino) file in the LucidVR project for more info.

**Comment by lhn3149** [comment]
There is a misunderstanding in pins number.
From the schematic symbol I have, the pin ( for example D17. D36,...) does not match your description with my intended use. 
My symbol does not have D36, D17.
I put some annotations on the schematics as well as the excel listing all the connections on 2 boards.

![pin-layout-list](https://user-images.githubusercontent.com/44926107/215305675-76722261-8a26-4789-9691-99be80df3351.PNG)
![pin-pattern](https://user-images.githubusercontent.com/44926107/215305676-b4989dc6-bec6-486b-8253-14be139bfb6d.PNG)

**Comment by WillNilges** [comment]
Gotcha, thanks for updating that.

What I'm saying, though, is that there's several major issues: 

1. In the firmware configuration, certain pins are used for certain functions. As a rule, we must maintain feature parity with the lucidVR firmware in order to make cooperation and upstreaming changes as easy as possible, so the pins you are using on these boards are wrong.
2. The positive voltage rails for the servos and potentiometers are flipped. The servos need 5V and the potentiometers need 3.3V
3. There seems to be a surplus of pins on this design. We only need 30 pins (10 signal, 10 ground, 10 power) for the servos and pots, plus an extra two for for the DOME (hypothetically), and this design seems to have redundant pins sprinkled throughout it that make it very difficult to make sense of. 
4. Nothing is labeled on the silkscreen, which makes it even more difficult to assemble. While it's possible to reference the diagram to remedy this, you shouldn't have to. Just put the labels on the silkscreen.

**Comment by WillNilges** [comment]
One more thing I noticed, your ESP32 symbol is labeled incorrectly. Here's what it should look like:
![image](https://user-images.githubusercontent.com/42927786/215354880-190f0de3-5e92-4fb2-8681-3fff973a8790.png)

**Comment by WillNilges** [comment]
Upon closer inspection, I see the intention with the power rails—it now appears that the signal pins are switched. If you look at the [LucidVR Firmware Config](https://github.com/LucidVR/lucidgloves/blob/8515b110362a13a2abf119d287870a31e65aa666/firmware/lucidgloves-firmware/lucidgloves-firmware.ino), that becomes obvious. All the pots are supposed to be relegated to one row of pins on one side, and the servos on the other, but that's switched. Apart from a few that are straight-up wrong.

**To be abundantly clear: [This file](https://github.com/LucidVR/lucidgloves/blob/8515b110362a13a2abf119d287870a31e65aa666/firmware/lucidgloves-firmware/lucidgloves-firmware.ino) is our source of truth for the signal pins. We must follow this as closely as we can.**

**Comment by lhn3149** [comment]
![3p3V_connection](https://user-images.githubusercontent.com/44926107/215545115-3d1636d2-3638-4264-826b-ab7c22d4c89f.PNG)
![5V-connection](https://user-images.githubusercontent.com/44926107/215545119-a421dac7-3865-4c33-9f5b-c7797db75e0d.PNG)
Yes, the 5V goes on the top but only connects to 1 pin (for the DOME), the majority is used to power the top plate where all the servos are connected. the 3.3V power is at the bottom and runs (blue wire) across the pins for potentiometers.

Other than that, I think we need to discuss today looking at the board.

**Comment by WillNilges** [comment]
The philosophy that I would prefer to follow with this design, if we go with it, is to separate voltage levels. All the 3v3 pins should be on one row, and all the 5v pins should be on the other.

**Comment by WillNilges** [comment]
Closed with Revision B (#9 )
